feat(gitoid): Add BoringSSL backend support for SHA-1 and SHA-256 in gitoid
omnibor/omnibor-rs pull request #182
Opened 2024-05-30 01:58 UTC by fkautz

This commit introduces support for the BoringSSL backend for SHA-1 and
SHA-256 in the gitoid Rust package. The SHA-1CD algorithm is not
supported with this backend. To enable BoringSSL, use the "boring"
feature in Cargo.

Additionally, benchmarks have been added to measure the performance
of the implemented cryptographic algorithms.

Signed-off-by: Frederick F. Kautz IV <fkautz@alumni.cmu.edu>

2024-06-03 15:52 UTC, alilleybrinker requested changes
Thanks so much @fkautz! I was out on vacation and am catching up with things now.

After some quick review, I think I have a couple of thoughts:

- The conditional compilation annotations on each item in the `boring_sha.rs` module can be removed, since the module itself is conditionally compiled.
- For the feature setup, I actually think I'd prefer a slightly different logic. In the current library, there's only one "crypto backend" (actual hash implementation provider), the RustCrypto one. With your PR, we're adding a BoringSSL one, which your PR conditionally swaps in if the `boring` feature is present. I think it would be good to instead have two features: `rustcrypto` and `boringssl`, which introduce their respective backend, and with the two backends both being usable if enabled. `boringssl` should always activate `sha1` and `sha256` since it unconditionally provides both when compiled. `rustcrypto` should not automatically activate _any_ algorithms, since all can be conditionally compiled out. If `sha1cd` is active and _only_ the `boringssl` backend is active, it should be a compilation error since `boringssl` can't provide that algorithm.

2024-06-05 04:54 UTC, fkautz commented
@alilleybrinker i hope i implemented your recommendations faithfully. let me know if there are any other issues.

2024-06-12 21:34 UTC, alilleybrinker reviewed
Thanks @fkautz! I think the feature setup is _almost_ but not quite what I was trying to describe. In particular, it should be possible to have both the `rustcrypto` and `boringssl` (I recommend naming the feature this name instead of `boring`, for accuracy) features active at the same time, with users then being able to select one at _runtime_ rather than only compile time if they'd like. So you'd want to introduce a new module called `rustcrypto` and move the code for activating the `rustcrypto` impls of the appropriate traits into there, and have it be based _only_ on whether the `rustcrypto` feature is active, not the presence of the `boringssl` feature.

Hopefully that helps clarify things!

2024-06-24 00:56 UTC, alilleybrinker approved these changes

2024-06-24 00:56 UTC, merged